version: '3.4'

services:
  reactcalcimc:
    image: reactcalcimc
    build:
      context: react_calc_imc
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
